MMS4 Support, Branding Service, Configuration File
Open-MBEE/ve pull request #141
Opened 2021-08-27 20:29 UTC by Enquier

This update adds

1. A Config file at the root to enable easier microservice/deployment management 
2. Token authentication and MMS4 support (in test)
3. Branding updates and services for adding banners and login messages.

2021-09-08 16:16 UTC, Enquier commented
I've now merged and incorporated the changes from the BA branch

2021-09-21 20:40 UTC, Enquier commented
This is now tested and working to the same level as the BA branch. I also backed out most of the OMG specific changes

2021-09-24 00:06 UTC, dlamoris requested changes
first pass, main thing is using the http interceptor instead of passing headers for each call, also with the ckeditor upgrade i don't remember if there's anything else we do, i think the config file was commented out because it depends on where ve actually gets deployed, stuff in there may be incorporated into the directive? guess we'll see

2021-09-24 00:19 UTC, Enquier commented
Thanks Doris. I think the interception differential was due to my older changes and me not being aware of it. I’ll make that change and look at the others on Monday

2021-09-24 00:21 UTC, dlamoris commented on src/directives/mmsCkEditor.js
> +                customConfig: '/lib/ckeditor/config.js',
actually i think it'll grab it at the right place if it's not defined, otherwise it'll get it at the absolute. url

2021-09-28 22:11 UTC, Enquier commented on app/js/mms/app.js
> +                template: '<ve-footer mms-footer="footer" ng-if="ve_footer"></ve-footer>',
ve-footer is now a separate controller which is why it's set there

2021-09-29 15:26 UTC, Enquier commented on Gruntfile.js
> +
Looks like those might have been added after my grunt file. I have re added them

2021-09-29 21:09 UTC, Enquier commented on app/config/config.example.js
> +        baseUrl: '',
Updated README.md and added new docs/Config.md

2021-09-29 21:15 UTC, Enquier commented on app/js/mms/controllers/main.controller.js
> +    $rootScope.ve_footer = "Proprietary Information - Not for Public  Release or Redistribution.";
It always gets replaced. However, removing it causes the footer to not work

2021-09-29 21:21 UTC, Enquier commented on app/partials/mms/diff-nav.html
> +<header role="banner">
Looks like this is an old file. Removed.

2021-09-29 21:22 UTC, Enquier commented on app/partials/mms/full-doc.html
> +            <div ng-repeat="view in views track by view.id" ng-class="{chapter: view.topLevel}">
Fixed.

2021-09-29 21:42 UTC, Enquier commented on src/directives/mmsViewLink.js
> +                        } else if (ViewService.isSection(pe)) {
Fixed.

2021-09-29 21:43 UTC, Enquier commented on src/directives/mmsViewLink.js
> +                        if (data._veNumber) {
Fixed

2021-09-29 21:44 UTC, Enquier commented on src/lib/ckeditor/config.js
>  	//config.tabSpaces = 4;
It was years ago now, but I remember that not having the config was an issue after upgrading CKEditor. Could be a difference in versions?

2021-09-29 21:46 UTC, Enquier commented on src/services/ElementService.js
> +        var defaultConfig = URLService.getRequestConfig();
Fixed

2021-10-10 22:18 UTC, dlamoris commented
this version is on https://opencae-uat.jpl.nasa.gov/mms4ve/mms.html currently, talking to cae-mms-uat-lb.jpl.nasa.gov

2021-12-13 19:54 UTC, merged