Artifacts and new Session/Event/Tree/Tool/Edit services part 2
Open-MBEE/ve pull request #144
Opened 2022-01-25 23:31 UTC by Enquier

Features:
- New Session, Event, Tree, Toolbar, and Edit services
Addition of these services are the first major step toward possibly moving View Editor from AngularJS to Angular. They remove dependencies on rootScope and the associated event systems which don't exist in Angular.
Additionally, they make VE to more stable through interruptions such as browser refreshing.

- MMS4 Artifact Support
Added support for viewing artifacts stored by MDK5+ in MMS4 as well as the ability to store images and files in MMS4 via CKEditor.

Bug Fixes:
- Fixed a bug where reloading the app on a document would cause the tree to reset to a single item
- Fixed a bug where uploaded artifacts were saving the token of the current session to the object/text rather than allowing the Auth to get intercepted by AngularJS
- Fixed several bugs where variables for username and project name in the UI were not updated to match new MMS4 patterns

2022-01-25 23:32 UTC, Enquier commented
This is a follow on to:
 #143

2022-02-03 19:03 UTC, dlamoris requested changes

2022-02-03 22:14 UTC, Enquier commented on app/js/mms/controllers/main.controller.js
> +    rootScopeSvc.veTitle('');
The Session service automatically emits the event every time the value changes

2022-02-03 22:36 UTC, Enquier commented on app/js/mms/controllers/main.controller.js
> +    rootScopeSvc.veTitle('');
That being said you are right about this being redundant, will fix

2022-02-03 22:36 UTC, Enquier commented on app/js/mms/controllers/main.controller.js
> +        rootScopeSvc.veViewContentLoading(true);
The Session service automatically emits the event every time the value changes

2022-02-03 22:37 UTC, Enquier commented on app/js/mms/controllers/toolbar.controller.js
> +    eventSvc.$init($scope);
Fixed

2022-02-03 22:37 UTC, Enquier commented on app/js/mms/controllers/view.controller.js
> +        tree.on_treeData_change();
Yes, this issue was what was causing the problems with the forward back buttons

2022-02-03 22:38 UTC, Enquier commented on app/js/mms/controllers/view.controller.js
> +        tree.on_treeData_change();
Yes, adding this line was what was causing the problems with the forward back buttons

2022-02-03 22:39 UTC, Enquier commented on app/js/mms/controllers/view.controller.js
> +                eventSvc.$broadcast('mms-pane-toggle', {closed: false});
Fixed

2022-02-03 22:39 UTC, Enquier commented on src/directives/mmsTree.js
> +            $scope.treeRows.length = 0;
I will take it out and test to make sure

2022-02-03 22:46 UTC, Enquier commented on src/services/SessionService.js
> +        return result;
This is the Session Service code that RootScopeService calls. By default an event is emitted with the name of the value each time it's changed

2022-02-03 22:49 UTC, Enquier commented on app/js/mms/controllers/fulldoc.controller.js
> +                eventSvc.$broadcast('tree-pane-toggle');
Fixed

2022-02-03 22:50 UTC, Enquier commented on app/js/mms/controllers/tool.controller.js
> +                var next = editSvc.getAll()[0];
The openEdits Command returns the result of Object.keys

2022-02-03 22:51 UTC, Enquier commented on src/directives/mmsTree.js
> +            $scope.treeRows.length = 0;
I took it out and seems to work so resolving

2022-02-03 22:52 UTC, Enquier commented on src/services/SessionService.js
> +        return result;
Note that I just realized I had the default wrong. Fixing

2022-02-03 23:24 UTC, dlamoris commented on app/js/mms/controllers/tool.controller.js
> +                var next = editSvc.getAll()[0];
i meant the editSvc.getAll part, that returns an object, can't do [0] on it

2022-02-03 23:27 UTC, Enquier commented on app/js/mms/controllers/tool.controller.js
> +                var next = editSvc.getAll()[0];
Noted

2022-02-03 23:30 UTC, Enquier commented on app/js/mms/controllers/tool.controller.js
> +                var next = editSvc.getAll()[0];
Fix pushed

2022-02-03 23:54 UTC, dlamoris commented on src/services/SessionService.js
> +        return result;
i think setting the emit to true by default is causing the tree filter (on what to show - tables, all, just views etc) to run into a loop/stack overflow, it's probably better to set it to true in the rootScopeSvc for ones that we want to emit as it's set - i think only the veContentLoading, title, and initialSelectionChange would matter, the others don't need to be emitted since those should already be calling event directly

2022-02-03 23:57 UTC, dlamoris commented on app/js/mms/controllers/view.controller.js
> +        tree.on_treeData_change();
maybe that was before the event fixes? i just tried it without and it seems to work

2022-02-04 18:34 UTC, Enquier commented on app/js/mms/controllers/view.controller.js
> +        tree.on_treeData_change();
Sounds good. I removed it

2022-02-04 18:38 UTC, Enquier commented on src/services/SessionService.js
> +        return result;
Okay I did a quick search and added the emit true to those that had events listening to them

2022-02-04 21:35 UTC, merged